### ISSUE TITLE
Does not give value to MG811

### ISSUE THREAD

**Issue by pjozsi** [nnaumenko/iot_ambit#21]
Hi!
I am struggling with a problem for some time, software do not calculate the  for the MG811
values. Everything else works flawlessly.
I upload the latest binary. What am I doing wrong, what's wrong?
Serial monitor image attached.
Thanks
![iot3](https://user-images.githubusercontent.com/33220393/32166857-6bd9609c-bd67-11e7-8ab3-fbb0d6bed8ad.jpg)

**Comment by nnaumenko** [comment]
This appears to be a bug in calculation of calibration data, just fixed it and updated a binary file. Thanks for reporting.

**Comment by pjozsi** [comment]
It works great! Thanks
